{{
    config(
        materialized='view',
        alias='sub_stage'
    )
}}

WITH raw_sub AS (
    SELECT * FROM {{ source('raw', 'raw_sub') }}
)

SELECT
    CAST(ADSH AS VARCHAR(20)) AS ADSH,
    CAST(CIK AS VARCHAR(10)) AS CIK,
    CAST(NAME AS VARCHAR(150)) AS NAME,
    CAST(SIC AS VARCHAR(4)) AS SIC,
    CAST(COUNTRYBA AS CHAR(2)) AS COUNTRYBA,
    CAST(STPRBA AS CHAR(2)) AS STPRBA,
    CAST(CITYBA AS VARCHAR(30)) AS CITYBA,
    CAST(ZIPBA AS VARCHAR(10)) AS ZIPBA,
    CAST(BAS1 AS VARCHAR(40)) AS BAS1,
    CAST(BAS2 AS VARCHAR(40)) AS BAS2,
    CAST(BAPH AS VARCHAR(20)) AS BAPH,
    CAST(COUNTRYMA AS CHAR(2)) AS COUNTRYMA,
    CAST(STPRMA AS CHAR(2)) AS STPRMA,
    CAST(CITYMA AS VARCHAR(30)) AS CITYMA,
    CAST(ZIPMA AS VARCHAR(10)) AS ZIPMA,
    CAST(MAS1 AS VARCHAR(40)) AS MAS1,
    CAST(MAS2 AS VARCHAR(40)) AS MAS2,
    CAST(COUNTRYINC AS CHAR(3)) AS COUNTRYINC,
    CAST(STPRINC AS CHAR(2)) AS STPRINC,
    CAST(EIN AS VARCHAR(10)) AS EIN,
    CAST(FORMER AS VARCHAR(150)) AS FORMER,
    CAST(CHANGED AS DATE) AS CHANGED,
    CAST(AFS AS VARCHAR(5)) AS AFS,
    CAST(WKSI AS BOOLEAN) AS WKSI,
    CAST(FYE AS VARCHAR(4)) AS FYE,
    CAST(FORM AS VARCHAR(10)) AS FORM,
    CAST(PERIOD AS DATE) AS PERIOD,
    CAST(FY AS INTEGER) AS FY,
    CAST(FP AS VARCHAR(2)) AS FP,
    CAST(FILED AS DATE) AS FILED,
    CAST(ACCEPTED AS TIMESTAMP) AS ACCEPTED,
    CAST(PREVRPT AS BOOLEAN) AS PREVRPT,
    CAST(DETAIL AS BOOLEAN) AS DETAIL,
    CAST(INSTANCE AS VARCHAR(40)) AS INSTANCE,
    CAST(NCIKS AS INTEGER) AS NCIKS,
    CAST(ACIKS AS VARCHAR(120)) AS ACIKS
FROM raw_sub
WHERE
    ADSH IS NOT NULL AND
    CIK IS NOT NULL AND
    NAME IS NOT NULL AND
    COUNTRYBA IS NOT NULL AND
    CITYBA IS NOT NULL AND
    COUNTRYINC IS NOT NULL AND
    WKSI IS NOT NULL AND
    FYE IS NOT NULL AND
    FORM IS NOT NULL AND
    PERIOD IS NOT NULL AND
    FY IS NOT NULL AND
    FP IS NOT NULL AND
    FILED IS NOT NULL AND
    ACCEPTED IS NOT NULL AND
    PREVRPT IS NOT NULL AND
    DETAIL IS NOT NULL AND
    INSTANCE IS NOT NULL AND
    NCIKS IS NOT NULL